### ISSUE TITLE
ADB开启 Wi-Fi 调试 会断连

### ISSUE THREAD

**Issue by eggdkk** [tongcheng-security-team/AppScan#1]
**Appscan 版本*

**系统版本**
1.电脑 
OS 名称:          Microsoft Windows 10 企业版
OS 版本:          10.0.19044 暂缺 Build 19044
2.手机
![image](https://user-images.githubusercontent.com/45118685/227504811-9ed3a357-7dec-47c9-bc69-63b0fe863c57.png)

**Bug 描述**
adb无线调试，点击开始合规检测 会断连
**Bug 重现步骤(有截图更好)**
1. RT

**Comment by ChnMig** [comment]
你好, app-scan目前只支持通过USB连接

**Comment by ChnMig** [comment]
你好, 未接到你的进一步回复, 此issue暂时关闭, 如你有其他问题欢迎继续提问, 谢谢
