### ISSUE TITLE
oppo r9 安卓5.1已root，连接时权限已给，但是还是检测不到手机

### ISSUE THREAD

**Issue by Small-ears** [tongcheng-security-team/AppScan#10]
*Appscan 版本

系统版本
电脑: ( win10)
2.手机: (oppo r9tm，coloros v3.0,android 5.1)

Bug 描述
手机已开启USB调试，oem锁，且本机电脑使用adb能正常连接以及root，但是appscan检测不到手机环境；
![image](https://user-images.githubusercontent.com/56350031/232457972-032369d3-8985-47e5-ab49-241fd3be2996.png)

**Comment by Small-ears** [comment]
*Appscan 版本

系统版本
电脑: ( win10)
2.手机: (oppo r9tm，coloros v3.0,android 5.1)

Bug 描述
手机已开启USB调试，oem锁，且本机电脑使用adb能正常连接以及root，但是appscan检测不到手机环境；
![image](https://user-images.githubusercontent.com/56350031/232457294-43328622-c893-443d-bfe5-3a631a631eb8.png)

**Comment by ChnMig** [comment]
你好, 目前低版本安卓有兼容问题, 我们近期会推送新版本修复, 同时需要说明的是, 即使是之后的新版本, appScan在安卓版本8以下也会因为某些adb命令不支持导致检测失败, 请更换新的安卓版本手机测试, 谢谢你
