### ISSUE TITLE
建议在结果导出按钮增加筛选功能

### ISSUE THREAD

**Issue by leoisnoob** [tongcheng-security-team/AppScan#11]
**Appscan 版本*
1.6
**系统版本**
1.电脑: mac
2.手机: oppo oneplus

**Bug 描述**
导出结果进行筛选
**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/43715055/233248469-08e8f415-d89e-4e36-b79b-3ee6e8263368.png)
2.
3.

**Comment by ChnMig** [comment]
您指的是, 点击mac地址后, 点击导出只到处mac地址相关的隐私合规数据吗?

**Comment by ChnMig** [comment]
未能进一步沟通, 此issue暂时关闭
