### ISSUE TITLE
无法触发检测任务

### ISSUE THREAD

**Issue by xuyiwei11** [tongcheng-security-team/AppScan#12]
**Appscan 版本*
1.7

**系统版本**
1.电脑:  win10
2.手机: one plus - Android 10

**Bug 描述**
点击”“开始检测”后，弹窗“已有app在检测中”，但实际并没有APP在检测任务列表中。

**Bug 重现步骤(有截图更好)**
1.
<img width="314" alt="1" src="https://user-images.githubusercontent.com/131328862/233252442-fd371e54-efb2-4289-b8ac-930f973f1cc4.png">

**Comment by xuyiwei11** [comment]
> 您好, 您之前是否有app在检测? 之后没有停止检测该app呢?

检查过了，之前没有APP在检测~

**Comment by ChnMig** [comment]
你好, 你可以加一下我们的官方微信群, 我来发给你一个修复包
![image](https://user-images.githubusercontent.com/44669684/233321715-2bd821a9-8c56-46d0-8221-9c1593bfae40.png)

**Comment by ChnMig** [comment]
您好, 1.0.8版本已推送, 请安装更新
