### ISSUE TITLE
小米6开始检测后，拉起app弹窗提示 Waiting For Debug

### ISSUE THREAD

**Issue by qzlinfox** [tongcheng-security-team/AppScan#14]
**Appscan 版本**
1.0.8

**系统版本**
1.电脑: MacOS 12.4 
2.手机: 小米6 Android11
OSVersion | 11
-- | --
VersionSDK | 30
ProductBrand | Xiaomi
CPUArchitecture | arm64-v8a
DeviceName | sagit
ProductModel | MI 6
ProductName | lineage_sagit
UDID | d99e9d37
CPUModel | Qualcomm Technologies, Inc MSM8998
CPUCoreNum | 8
MemoryTotal | 6GB

**Bug 描述**
小米6开始检测后，拉起app弹窗提示 Waiting For Debug

**Bug 重现步骤(有截图更好)**
1. 插上手机
2.打开Appscan
3.在应用列表选择应用开始检测
4. 拉起app，之后就弹窗提示 Waiting For Debug

![img_v2_3802bc3d-bb68-45fd-a754-82326cee7b0g](https://user-images.githubusercontent.com/86899005/234260764-08fb306c-b01c-4748-ae72-62e576b80572.jpg)

**Comment by ChnMig** [comment]
您好, 目前已知个别ROM会偶发出现, 您可以尝试使用 adb 运行 `adb shell am clear-debug-app` 后使用appScan查看是否能解决问题, 如能解决请留言回复, 帮助我们采集方案, 谢谢你

**Comment by qzlinfox** [comment]
尝试了几次，使用 adb 运行 adb shell am clear-debug-app 后使用appScan查看无法解决

**Comment by qzlinfox** [comment]
另外，关闭AppScan后卡住的App正常继续打开了

**Comment by qzlinfox** [comment]
暂时没有，手里root的手机只有这台了

**Comment by ChnMig** [comment]
使用 adb shell am clear-debug-app 这个命令后有什么输出吗?

**Comment by qzlinfox** [comment]
试了下，没有输出
![image](https://user-images.githubusercontent.com/86899005/236100062-fcd4a37a-c14b-41ed-b811-4bd433d3d239.png)

**Comment by ChnMig** [comment]
我这里没有复现这个问题, 要不您加一下交流群, 然后说一下您的问题, 我来加您微信看看

**Comment by ChnMig** [comment]
未接到您的进一步反馈, 暂时关闭这个issue
