### ISSUE TITLE
插上root手机后，点击“请连接到设备开始隐私合规检测”后，无法进入到“应用列表页”，关闭应用重新启动也无效

### ISSUE THREAD

**Issue by qzlinfox** [tongcheng-security-team/AppScan#15]
**Appscan 版本*
1.0.8

**系统版本**
1.电脑: MacOS 12.4
2.手机: Google Pixel XL 安卓10

**Bug 描述**
插上root手机后，点击“请连接到设备开始隐私合规检测”后，无法进入到“应用列表页”，关闭应用重新启动也无效，但是点击历史再点击检测tab，就可以查看应用列表

**Bug 重现步骤(有截图更好)**
1.插上手机
2.点击“请连接到设备开始隐私合规检测”后
3.点击历史tab
4.点击检测tab

https://user-images.githubusercontent.com/86899005/234262590-34fb3162-eaa5-41a9-b71f-729e82db9eec.mp4

**Comment by ChnMig** [comment]
你好, 这是目前已知的用户体验问题, 已知的会在某些性能较差的手机上偶发, 我们已经排期优化, 目前您可以正常的通过切换tab来进行检测, 或者尝试重启app

**Comment by qzlinfox** [comment]
了解，感谢大佬解答～
