### ISSUE TITLE
建议在“结果导出”增加筛选逻辑

### ISSUE THREAD

**Issue by leoisnoob** [tongcheng-security-team/AppScan#16]
**Appscan 版本*

**系统版本**
1.电脑: (例如 win10)
2.手机: (例如 红米k40-安卓11)

**Bug 描述**
建议在结果导出的按钮增加筛选的逻辑，仅导出按钮当前的输出结果
比如：
我点击“android ID” 标签，输出3个记录，然后点击结果导出之后，excel表就导出了这三个记录
![image](https://user-images.githubusercontent.com/43715055/235035763-1996aee1-e181-424e-8f3c-4756ebcd7de6.png)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by ChnMig** [comment]
目前暂不支持此功能, 您可以尝试在excel中设置筛选来解决这个问题
