### ISSUE TITLE
增加pdf报告功能

### ISSUE THREAD

**Issue by zhangleisec** [tongcheng-security-team/AppScan#17]
pdf报告便于开发者处理相关问题

**Comment by ChnMig** [comment]
您希望pdf中包含什么内容呢?

**Comment by ChnMig** [comment]
明白了, 但是这个功能需要软件自动进行判断和处理, 我们也正在评估是否需要提高自动化方面的能力, 您可以先使用导出到world的功能, 并期待后续更新, 谢谢你的建议.
