### ISSUE TITLE
模拟器识别功能增加

### ISSUE THREAD

**Issue by zhangleisec** [tongcheng-security-team/AppScan#18]
夜神模拟器 和 木木模拟器 支持识别检测

目前大部分品牌手机root 都会失去维保的权益.
建议增加模拟器识别   这样就不用root手机

**Comment by turnsgreen** [comment]
> 感谢反馈, 我们确实接收到不少这样的需求, 后续会进行评估和开发, 感谢您的支持和使用.

o(_ _)o 期待尽快开源，像这样的需求其实可以让社区提 pr 来完成~

**Comment by ChnMig** [comment]
> > 感谢反馈, 我们确实接收到不少这样的需求, 后续会进行评估和开发, 感谢您的支持和使用.
> 
> o(_ _)o 期待尽快开源，像这样的需求其实可以让社区提 pr 来完成~

感谢回复, 目前开源涉及到内部章程, 进度较慢, 我们也会一直推进
支持模拟器的需求也列入了开发清单, 等我们人力释放后会及时处理, 感谢使用
