### ISSUE TITLE
frida防检测建议

### ISSUE THREAD

**Issue by ipsecc** [tongcheng-security-team/AppScan#20]
我在使用camille时，遇到过一些由于检测了frida导致无法正常启动的app。camille中存在一个-H参数，可以通过换端口启动并指定Frida-sever，从而绕过检测。
![image](https://github.com/tongcheng-security-team/AppScan/assets/40918024/cb062dfe-c714-4b66-a417-2177ddce5bda)

希望Appscan也可以引入这个配置项。

**Comment by ChnMig** [comment]
感谢反馈, 我会将这个需求记录, 让我们评审一下, 谢谢你
