### ISSUE TITLE
报错 list index out of range 是啥原因？

### ISSUE THREAD

**Issue by fnatic0606** [tongcheng-security-team/AppScan#3]
**Appscan 版本*

**系统版本**
1.电脑
2.手机

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by ChnMig** [comment]
你好, 请提供bug出现的场景方便排查, 谢谢

**Comment by ChnMig** [comment]
因长时间未回复, 此issue暂时关闭, 谢谢
