### ISSUE TITLE
无应用列表显示

### ISSUE THREAD

**Issue by nmgswkj** [tongcheng-security-team/AppScan#4]
**Appscan 版本*
v1.0.5
**系统版本**
1.电脑 
机械革命银翼战神
2.手机
OPPO R9S
**Bug 描述**
进行到“正在为您在进行adb工具初始化..”，结束后无应用列表显示，尝试了如下操作：
①以管理员身份重启应用
②重启手机
③重启USB调试和开发者模式

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/127916127/227874073-e4251187-f452-4344-bd9b-801d3eede5a0.png)

**Comment by ChnMig** [comment]
你好, 请尝试重启appScan

**Comment by nmgswkj** [comment]
重启了好几次了，依然是这个状态。
现在把USB配置改成“仅限充电”，重启以后再开启APP，就一直停留在了“正在为您在进行adb工具初始化...”，大概有十多分钟了，还在这一步~~~
![image](https://user-images.githubusercontent.com/127916127/227876789-9aa85413-237e-4558-85c8-042604216c65.png)

**Comment by ChnMig** [comment]
你好, 手机端是否有弹出, 类似同意来自设备XXX的ADB调试窗口和ROOT申请呢

**Comment by ChnMig** [comment]
正常情况下会有权限申请的, 你可以排查一下手机端的adb调试设置是否正确, 比如开发者选项中的usb调试, usb安装等

**Comment by ChnMig** [comment]
因未接收到进一步反馈, 此issue暂时关闭
