### ISSUE TITLE
检测就是闪退

### ISSUE THREAD

**Issue by VVeakee** [tongcheng-security-team/AppScan#6]
**Appscan 版本*

**系统版本**
1.机械革命code01
2.pixel2

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.adb给了root权限
2.开始检测,打开了某app
3.某app已停止运行
4.手机重启后,再次操作
5.开始检测,手机没反应了
还是差点意思

**Comment by ChnMig** [comment]
请问安卓版本是多少

**Comment by VVeakee** [comment]
8.1

..........
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tongcheng-security-team/AppScan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月27日(星期一) 晚上7:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tongcheng-security-team/AppScan] 检测就是闪退 (Issue #6)





 
请问安卓版本是多少

**Comment by ChnMig** [comment]
非常感谢, 目前已知安卓低版本有兼容问题, 正在修复. #7

**Comment by ChnMig** [comment]
新版本已推送, 麻烦测试一下

**Comment by VVeakee** [comment]
已经可以检测到app,但是正在检测一个app中返回了一下就找不到检测的页面了,只能看到这个
显示已有app在检测,但是找不到正在检查的app那那个页面



..........
***@***.***




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tongcheng-security-team/AppScan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月19日(星期三) 晚上7:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tongcheng-security-team/AppScan] 检测就是闪退 (Issue #6)





 
新版本已推送, 麻烦测试一下

**Comment by ChnMig** [comment]
返回指的是跳到软件列表页吗? 软件列表页每一个app后有按钮, 如果是正在检测的app会有停止检测和继续检测两个按钮和其他app区分的, 您看一下呢? 或者截个图发一下

**Comment by VVeakee** [comment]
视频
录制_2023_04_19_20_23_10_196.mp4 https://www.aliyundrive.com/s/QPjGNdfYXdF 点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。


..........
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tongcheng-security-team/AppScan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月19日(星期三) 晚上8:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tongcheng-security-team/AppScan] 检测就是闪退 (Issue #6)





 
返回指的是跳到软件列表页吗? 软件列表页每一个app后有按钮, 如果是正在检测的app会有停止检测和继续检测两个按钮和其他app区分的, 您看一下呢? 或者截个图发一下

**Comment by ChnMig** [comment]
你好, 请在app列表页查找是否有上次未检测完的app. 然后通过点击 继续检测 继续检测或者点击 停止检测 来停止上一次检测, 开始新的检测

**Comment by ChnMig** [comment]
![image](https://user-images.githubusercontent.com/44669684/233240424-e1bdea26-abac-40ef-a8af-350b1903d9d7.png)
类似这样

**Comment by ChnMig** [comment]
您好, 1.0.8版本已推送, 请安装更新
