### ISSUE TITLE
进行到“获取手机应用列表”后返回到“无法连接的原因”界面。

### ISSUE THREAD

**Issue by FluteY2** [tongcheng-security-team/AppScan#8]
**Appscan 版本*

**系统版本**
1.电脑: win10
2.手机: 小米mix3 安卓10

**Bug 描述**

**Bug 重现步骤(有截图更好)**、
1. 打开了usb调试和adb，手机连电脑弹出过来自设备xxx的ADB调试，并已同意。
2. 点击开始检测后，AppScan显示“正在为您进行adb工具初始化”阶段，并在手机上弹出过“shell已授予超级用户权限”
3. 有时进行到“获取手机应用列表”后返回到“无法连接的原因”界面。，有时直接在“正在为您进行adb工具初始化”后返回到“无法连接的原因”界面。
4. 多次尝试重启仍然遇到同样问题

**Comment by TheBestLL** [comment]
我们已经知晓该问题, 正在协调相关资源, 定位和处理问题中. 处理完成会第一时间推送升级包。 #7

**Comment by VVeakee** [comment]
1.0.6仍旧发现该问题,安卓8.1

**Comment by ChnMig** [comment]
你好, 目前新版本已推送
