### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by AceCoronnet9034** [tongcheng-security-team/AppScan#9]
首先感谢作者的开源，希望未来appscan能添加使用adb连接Mumu模拟器，毕竟需要扫描的应用大部分情况下用模拟器会安全一些。祝越来越好。

**Comment by ChnMig** [comment]
你好, 感谢你的建议
 appScan的初衷是帮助合规人员检测和发现自己的软件出现的违规问题, 避免app被下架,因此设计之初没有考虑到支持模拟器.
我们之后会评估需求的必要性, 而后再进行具体规划, 再次感谢你的建议.
